fix(config/searcher): fix error with fusuma-sendkey before loading keymap
$ fusuma-sendkey -l
NoMethodError: undefined method `find' for nil:NilClass ← location is not found
  fusuma/lib/fusuma/config/searcher.rb:37:in `search_with_context'
  fusuma/lib/fusuma/config/searcher.rb:50:in `block in search_with_cache'
  fusuma/lib/fusuma/config/searcher.rb:60:in `cache'
  fusuma/lib/fusuma/config/searcher.rb:49:in `search_with_cache'
  fusuma/lib/fusuma/config.rb:76:in `search'
  fusuma/lib/fusuma/config.rb:23:in `search'
  fusuma/lib/fusuma/plugin/base.rb:33:in `config_params'
  fusuma/lib/fusuma/plugin/inputs/libinput_command_input.rb:46:in `libinput_options'
  fusuma/lib/fusuma/plugin/inputs/libinput_command_input.rb:36:in `command'
  fusuma/lib/fusuma/device.rb:68:in `fetch_devices'
  fusuma/lib/fusuma/device.rb:39:in `all'
  fusuma-plugin-sendkey/lib/fusuma/plugin/sendkey/keyboard.rb:114:in `find_device'
  fusuma-plugin-sendkey/lib/fusuma/plugin/sendkey/keyboard.rb:15:in `initialize'
  fusuma-plugin-sendkey/exe/fusuma-sendkey:24:in `new'
  fusuma-plugin-sendkey/exe/fusuma-sendkey:24:in `<top (required)>'
  fusuma-sendkey:23:in `load'
  fusuma-sendkey:23:in `<top (required)>'